<!doctype html>
<html lang="en">
@include('admin.comment.head')
<body>
<div class="wrapper has-footer">
    @include('admin.comment.header')
    @include('admin.comment.aside')

 <div class="main-container">

    <div class="content-wrap">  <!--START: Content Wrap-->
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">面板标题</h3>
                        <div class="tools">
                            <a class="btn-link collapses panel-collapse" href="javascript:;"></a>
                            <a class="btn-link reload" href="javascript:;"><i class="ti-reload"></i></a>
                        </div>
                    </div>
                    <div class="panel-body">
                        <table class="table table-bordered table-dataTable">
                            <thead>
                            <tr>
                                <th>名字</th>
                                <th>职业</th>
                                <th>地点</th>
                                <th>年龄</th>
                                <th>开始日期</th>
                                <th>金额</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>名字</th>
                                <th>职业</th>
                                <th>地点</th>
                                <th>年龄</th>
                                <th>开始时间</th>
                                <th>薪水</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr><td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr><td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            <tr>
                                <td>刘欢</td>
                                <td>工程师</td>
                                <td>武昌</td>
                                <td>35</td>
                                <td>2016/04/25</td>
                                <td>320,800</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
    </div>  <!--END: Content Wrap-->
    @include('admin.comment.footer')
</div>  <!-- END: Main Container -->
@include('admin.comment.js')
</body>
</html>